src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (GoUserViewSet, ProblemCreateView, ProblemDeleteView,
                       ProblemDetailView, ProblemsListView, ProblemsUpdateView,
                       SolutionGetVew, SolutionListView)

router = routers.DefaultRouter()
router.register("users", GoUserViewSet)
app_name = "api"

# POST gamers/
# GET gamers/
# GET gamers/<id>/
# PUT gamers/<id>/
# PATCH gamers/<id>/
# DELETE gamers/<id>/

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

problems_urls = [
    path(
        "problems/retrieve/<int:pk>",
        ProblemDetailView.as_view(),
        name="problems_detail_api",
    ),
    path("problems/create/", ProblemCreateView.as_view(), name="problems_create_api"),
    path(
        "problems/update/<int:pk>",
        ProblemsUpdateView.as_view(),
        name="problems_update_api",
    ),
    path(
        "problems/delete/<int:pk>",
        ProblemDeleteView.as_view(),
        name="problems_delete_api",
    ),
    path("problems/list/", ProblemsListView.as_view(), name="problems_list"),
]

solution_urls = [
    path("solutions/get/<int:pk>", SolutionGetVew.as_view(), name="solution_get"),
    path("solutions/list/", SolutionListView.as_view(), name="solutions_list"),
]


urlpatterns = [
    path("", include(router.urls)),
    path("docs/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("auth/", include("djoser.urls.jwt")),
]
urlpatterns += problems_urls
urlpatterns += solution_urls

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from common.views import Error404, Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("problems/", include("problems.urls", namespace="problems")),
    path("forum/", include("forum.urls", namespace="forum"))
]
handler404 = Error404.as_view()
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/problems/urls.py
from django.urls import path

from problems.views import SolvedTask, Task, TaskList

app_name = "problems"
urlpatterns = [
    path("list/", TaskList.as_view(), name="list"),
    path("<int:pk>/", Task.as_view(), name="selected_task"),
    path("<int:pk>/sumbit/", SolvedTask.as_view(), name="solved_task"),
]

src/problems/models.py
import os
from random import choice, randint

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import CASCADE, SET_DEFAULT
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from faker import Faker

from common.models import BaseModel

# Create your models here.


class DIFFICULTLY_CHOICES(models.IntegerChoices):
    EASY = 0, "Easy"
    MEDIUM = 1, "Medium"
    HARD = 2, "Hard"


class TASK_STATUS_CHOICES(models.IntegerChoices):
    IN_DEVELOPMENT = 0, "In-Development"
    ACCEPTED = 1, "Accepted"


class Category(BaseModel):
    category = models.CharField(max_length=80)

    def __str__(self):
        return f"{self.category}"

    @classmethod
    def generate_categories(cls):
        categories = []
        choices = ["Math", "db", "algorithms"]
        for i in choices:
            category = Category(category=f"{i}")
            categories.append(category)
        result = Category.objects.bulk_create(categories)
        return result


class Language(BaseModel):
    language = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.language}"

    @classmethod
    def generate_languages(cls):
        languages = []
        choices = ["Python", "Java", "JavaScript", "C#", "C++"]
        for i in choices:
            language = Language(language=f"{i}")
            languages.append(language)
        result = Language.objects.bulk_create(languages)
        return result


class Tasks(BaseModel):
    name = models.CharField(
        max_length=280,
        unique=True,
        help_text=_("Name must be unique and max length is 280 characters."),
    )
    difficulty = models.PositiveSmallIntegerField(
        choices=DIFFICULTLY_CHOICES.choices, default=DIFFICULTLY_CHOICES.MEDIUM
    )
    category = models.ForeignKey(Category, on_delete=CASCADE)
    description = models.TextField(max_length=2400)
    constraints = models.CharField(max_length=240)
    tests = models.ForeignKey("problems.Tests", on_delete=CASCADE)
    photo = models.ImageField(upload_to="tasks/images", null=True, blank=True)

    def __str__(self):
        return f"({self.pk}){self.name} {self.difficulty} {self.category} {self.created_at}"

    @classmethod
    def generate_tasks(cls, count):
        tasks = []
        faker = Faker()
        for i in range(count):
            task = Tasks(
                name=faker.sentence(nb_words=5),
                difficulty=randint(0, 2),
                category=choice(Category.objects.all()),
                description=faker.text(max_nb_chars=2400),
                constraints=faker.text(max_nb_chars=240),
                tests=choice(Tests.objects.all()),
                photo=faker.image_url(),
            )
            tasks.append(task)
        result = Tasks.objects.bulk_create(tasks)
        return result

    def get_task_status(self, user_id):
        try:
            solution = Solutions.objects.get(task=self, user_id=user_id)
            return solution.status
        except Solutions.DoesNotExist:
            return None

    def get_count_solutions(self):
        return Solutions.objects.filter(task=self).count()


class Tests(BaseModel):
    count_tests = models.IntegerField()
    tests = models.FileField(upload_to="data_tests/")

    def __str__(self):
        return f"({self.pk}){self.tests} {self.count_tests}"

    @classmethod
    def generate_tests(cls, count):
        tests = []
        faker = Faker()
        for i in range(count):
            test = Tests(
                count_tests=count,
                tests=f"problems/tasks/tests_for_tasks/{faker.file_path()}",
            )
            tests.append(test)
        result = Tests.objects.bulk_create(tests)
        return result


class Solutions(BaseModel):
    user = models.ForeignKey(get_user_model(), on_delete=CASCADE, related_name="user")
    task = models.ForeignKey(Tasks, on_delete=CASCADE, related_name="solution")
    language = models.ForeignKey(
        Language,
        on_delete=CASCADE,
        related_name="solution_language",
    )
    solution = models.TextField(max_length=4200)
    status = models.PositiveSmallIntegerField(
        choices=TASK_STATUS_CHOICES.choices, default=TASK_STATUS_CHOICES.IN_DEVELOPMENT
    )
    time = models.PositiveIntegerField()
    memory = models.FloatField()
    test_passed = models.PositiveIntegerField()

    def __str__(self):
        return f"({self.pk}){self.user.username} {self.task.name} {self.language} status: {self.status} memory: {self.memory}mb time: {self.time}ms test_passed: {self.test_passed}"

    def get_date(self):
        return (timezone.now() - self.last_updated).days

    @classmethod
    def generate_solutions(cls, count):
        solutions = []
        faker = Faker()
        for i in range(count):
            user = choice(get_user_model().objects.all())
            task = choice(Tasks.objects.all())
            language = choice(Language.objects.all())
            solution = Solutions(
                user=user,
                task=task,
                language=language,
                solution=faker.text(max_nb_chars=4200),
                status=randint(0, 1),
                time=randint(1, 1000),
                memory=randint(1, 1000),
                test_passed=randint(0, 100),
            )
            solutions.append(solution)
        result = Solutions.objects.bulk_create(solutions)
        return result

src/problems/forms.py
from django import forms
from django.http import HttpResponse
from django_ace import AceWidget

from problems.models import Solutions


class EditorForm(forms.Form):
    text = forms.CharField(widget=AceWidget(mode="python", theme="monokai", fontsize="13px", toolbar=False))

    def clean_code(self):
        code = self.cleaned_data['text']
        print("\n\n\n\nvalidation....\n\n\n\n\n")
        # Пример проверки на запрещенные слова
        if "os" in code:
            raise forms.ValidationError("Использование 'import os' запрещено!")

        return code

src/problems/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from problems.forms import EditorForm
from problems.models import Category, Language, Solutions, Tasks
from problems.redis.utils import (add_in_queue, check_user_in_queue,
                                  wait_and_get_result)
from problems.utils.validators import validate_code

# Create your views here.


class TaskList(ListView):
    paginate_by = 25
    template_name = "task_list.html"
    queryset = Tasks.objects.all()
    context_object_name = "tasks"

    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)
        search_task = request.GET.get("search-task", False)
        category = request.GET.get("category", False)
        if search_task:
            return render(
                request,
                "task_list.html",
                context={"tasks": Tasks.objects.filter(name__icontains=search_task)},
            )
        elif category:
            try:
                get_category = Category.objects.get(category=category)
            except Category.DoesNotExist:
                return HttpResponse("Category does not exist.")
            return render(
                request,
                "task_list.html",
                context={"tasks": Tasks.objects.filter(category=get_category)},
            )
        return super().get(request, *args, **kwargs)


class Task(TemplateView):
    template_name = "selected_task.html"
    form_class = EditorForm
    task = None
    task_tests = None
    model = Solutions
    start = """def {name}(**kwargs):\n\tpass"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.task = Tasks.objects.get(pk=kwargs.get("pk", None))
        if self.task is None:
            return HttpResponse("No such task")
        context["task"] = self.task
        context["form"] = self.form_class(self.request.POST or None, initial={"text": self.format_start_code()})
        return context

    def get_start_code(self):
        try:
            code = Solutions.objects.get(task=self.task, user_id=self.request.user.id).solution
            return True, code
        except Solutions.DoesNotExist:
            return False, self.start

    def format_start_code(self):
        start = self.get_start_code()
        if start[0]:
            return start[1]

        name = self.task.name.replace(" ", "_").lower()
        return start[1].format(name=name)


class SolvedTask(TemplateView):
    template_name = "solved_task.html"
    form_class = EditorForm
    queue_data_name = "data"
    queue_pk_name = "pks"
    queue_result_name = "results"

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        # task = Tasks.objects.get(id=kwargs.get("pk"))
        if form.is_valid():
            code = form.cleaned_data["text"]
            is_valid_code = validate_code(code)
            if not is_valid_code[0]:
                return HttpResponse(f"Name '{is_valid_code[1]}' is not available, use another one")
            if check_user_in_queue(self.request.user.pk):
                return HttpResponse("you can't s sumbit 2 tasks at once")
            test = task.tests.tests.name
            data = json.dumps({"pk": self.request.user.pk, "code": code, "test_name": test.split("/")[-1]})

            add_in_queue(data, self.request.user.pk)

            result = wait_and_get_result(self.request.user.pk)

            update_solution = Solutions.objects.filter(
                user_id=self.request.user.pk,
                task=task
            ).update(
                status=result.get("status"),
                test_passed=result.get("successful_tests"),
                solution=code,
            )
            if not update_solution:
                solution = Solutions(
                    task=task,
                    user=request.user,
                    language=Language.objects.get(language="Python"),
                    solution=code,
                    status=result.get("status"),
                    time=16,
                    memory=4,
                    test_passed=result.get("successful_tests"),
                )
                solution.save()
            return render(
                request,
                self.template_name,
                context={"result": result},
            )

src/problems/templates/selected_task.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LeetCode-style Problem</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
{% block body %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <script src="{% static 'django_ace/ace.js' %}"></script>
    <script src="{% static 'django_ace/ext-language_tools.js' %}"></script>
    {{ form.media }}
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: rgb(28, 28, 28);
        }
        .django-ace-editor {
            border-radius: 10px;
        }
        .tabs {
            display: flex;
            background-color: #292929;
            color: #ffffff;
            padding: 10px 20px;
            border-radius: 8px 8px 0 0;
        }

        .tab {
            margin-right: 20px;
            font-size: 14px;
            font-weight: 500;
            color: #b0b0b0;
            text-decoration: none;
            cursor: pointer;
        }

        .tab:hover {
            color: #ffffff;
        }

        .tab-active {
            color: #ffffff;
            font-weight: bold;
        }

        /* Стили для основного контейнера задачи */
        .task-container {
            background-color: #323232;
            color: #dcdcdc;
            padding: 20px;
            border-radius: 10px;
            max-width: 800px;
            width: 60%;
            height: 770px;
            margin-top: 15px;
            margin-left: 40px;
            font-family: Arial, sans-serif;
        }

        /* Стили для заголовка задачи */
        .task-title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #ffffff;
        }

        /* Стили для тегов */
        .tags {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
        }


        /* Стили для описания */
        .task-description {
            font-size: 14px;
            line-height: 1.6;
            color: #c8c8c8;
        }

.container {
    display: flex;
    justify-content: space-between;
}

/* Контейнер с задачей (слева) */
.task-container {
    width: 1000px; /* Занимает 60% ширины */
    margin-left: -400px; /* Отступ слева */
}
.form-container p {
    display: none;
}

/* Контейнер с формой (справа) */
.ace_editor {
    width: 895px !important;   /* Устанавливает ширину редактора */
    height: 600px !important;  /* Устанавливает высоту редактора */
    border-radius: 10px;
}
.tabs a {
    text-decoration: none;
    color: #9f9f9f; /* Исходный цвет ссылки */
    transition: color 0.3s ease, transform 0.3s ease; /* Анимация цвета и увеличения */
}

.tabs a:hover {
    color: #ffffff; /* Цвет при наведении */
    transform: scale(1.1); /* Увеличение текста при наведении */
}

    </style>
<div class="container">
    <!-- Левый блок с задачей -->
    <div class="task-container">
        <!-- Вкладки -->
        <div class="tabs" style="width: 400px">
            <a href="#" class="tab tab-active">Description</a>
            <a href="#" class="tab">Editorial</a>
            <a href="#" class="tab">Solutions</a>
            <a href="#" class="tab">Submissions</a>
        </div>
        <!-- Заголовок задачи -->
        <div class="task-title">{{ task.pk }}. {{ task.name }}</div>

        <!-- Теги -->
        <div class="tags">
            {% if task.difficulty == 0 %}
                <div class="tag-difficultly" style="background-color: #3c3c3c; color: #73cf5e; padding: 3px 8px; border-radius: 5px; font-size: 12px; font-weight: bold;">{{ task.get_difficulty_display }}</div>
            {% elif task.difficulty == 1 %}
                <div class="tag-difficultly" style="background-color: #3c3c3c; color: #cd9738; padding: 3px 8px; border-radius: 5px; font-size: 12px; font-weight: bold;">{{ task.get_difficulty_display }}</div>
            {% else %}
                <div class="tag-difficultly" style="background-color: #3c3c3c; color: #d53939; padding: 3px 8px; border-radius: 5px; font-size: 12px; font-weight: bold;">{{ task.get_difficulty_display }}</div>
            {% endif %}
            <div class="tag-category" style="background-color: #3c3c3c; color: #919191; padding: 3px 8px; border-radius: 5px; font-size: 12px; font-weight: bold;">{{ task.category }}</div>
        </div>

        <!-- Описание задачи -->
        <div class="task-description">
            <h6 style="color: white; background-color: #494949; width: 765px; height: 23px;border-radius: 3px">note: Before you decide, get your arguments which are indicated in the description. kwargs.get("name_arg")</h6>
            {{ task.description }}
        </div>
    </div>

    <!-- Правый блок с формой -->
    <div class="form-container" style="margin-top: 17px; margin-left: 5px">
        <form method="post" action="{% url 'problems:solved_task' pk=task.pk%}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" style="margin-left: -8px;width: 100px; height: 30px; border: none; background-color: #424242; color: white; border-radius: 3px; font-size: 14px;" class="btn btn-dark">Submit</button>
        </form>
    </div>
</div>
<div class="under-code-editor" style="background-color: #333333; height: 155px; width: 896px; margin-top: -157px; border-radius: 10px; margin-left: 845px">
<div class="dropdown">
    <button style="background-color: #424242; margin-left: 120px; height: 30px; font-family: 'JosefinSans'; font-size: 14px; margin-top: 10px"
            class="btn btn-secondary dropdown-toggle"
            type="button"
            data-toggle="dropdown"
            aria-expanded="false">
        all languages
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
</div>
</div>
{% endblock body %}
</body>

</html>

src/problems/templates/task_list.html
{% extends 'base.html' %}
{% load static %}
{% load problems_list %}

<!DOCTYPE html>
<html lang="en">

<body>
{% block body %}
        <style>
        body {
            background: rgb(28, 28, 28);
        }
        .file-upload input[type="file"] {
            display: none; /* Скрываем стандартный элемент input */
        }

        .file-upload img {
            width: 120px; /* Задайте ширину изображения */
            height: auto; /* Высота автоматически подстраивается */
            border-radius: 105px; /* Скругление углов */
        }

        div.div-form-to-edit-profile {
            font-family: 'Calibri', sans-serif;
            font-size: 15px;
        }

/* Стилизация скроллбара для WebKit (Chrome, Safari) */
textarea {
    /* Устанавливаем ширину скроллбара */
    scrollbar-width: thin; /* Firefox */
    scrollbar-color: #682773 transparent;
    width: 100%;
    height: 120px;
    border-radius: 6px;
}

/* Для WebKit (Chrome, Safari) */
textarea::-webkit-scrollbar {
    width: 8px; /* Ширина скроллбара */
}

textarea::-webkit-scrollbar-thumb {
    background-color: #682773; /* Цвет скроллбара */
    border-radius: 10px; /* Скругление углов */
}

textarea::-webkit-scrollbar-track {
    background: transparent; /* Фон скроллбара */
}
    </style>
<div class="centered-div" style="display: flex; flex-direction: column; align-items: center;">
    <h5 style="color: white;">Problems</h5>
    <div style="background-color: #444444; margin-top: 10px; height: 1px; width: 100%;"></div>
    <div style="display: flex; align-items: center; margin-top: 10px;">
        <div class="btn-group" role="group" aria-label="Basic example" style="margin-right: 10px;">
            <a href="{% url 'problems:list' %}?category=Math" type="button" class="btn btn-secondary" style="height: 30px; font-size: 13px; font-family: 'JosefinSans'; margin-top: 10px; background-color: #424242;">Math</a>
            <a href="{% url 'problems:list' %}?category=db" type="button" class="btn btn-secondary" style="height: 30px; font-size: 13px; font-family: 'JosefinSans'; margin-top: 10px; background-color: #424242;">DB</a>
            <a href="{% url 'problems:list' %}?category=algorithms" type="button" class="btn btn-secondary" style="height: 30px; font-size: 13px; font-family: 'JosefinSans'; margin-top: 10px; background-color: #424242;">Algorithms</a>
        </div>
        <form method="get" action="{% url 'problems:list' %}" style="display: flex; align-items: center;">
            <input class="search-task" type="text" name="search-task" placeholder="Search task" style="flex: 1; height: 30px;">
            <button class="btn btn-secondary" type="submit" style="width: 80px; height: 30px; border: none; background-color: #424242; color: white; border-radius: 3px; font-size: 14px; margin-top: 10px">
                Search
            </button>
        </form>
<div class="dropdown">
    <button style="background-color: #424242; margin-left: 10px; height: 30px; font-family: 'JosefinSans'; font-size: 14px; margin-top: 10px"
            class="btn btn-secondary dropdown-toggle"
            type="button"
            data-toggle="dropdown"
            aria-expanded="false">
        all languages
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
</div>
    </div>
    <div style="width: 100%; margin-top: 20px;">
        <table style="width: 100%; border-collapse: collapse;">
            <thead>
                <tr style="background-color: rgba(0,0,0,0); color: white;">
                    <th style="padding: 10px;">Status</th>
                    <th style="padding: 10px; border-radius: 5px 0 0 5px;">Task Name</th>
                    <th style="padding: 10px;">Count solutions</th>
                    <th style="padding: 10px;">Category</th>
                    <th style="padding: 10px;">Difficulty</th>
                </tr>
                <!-- Разделительная линия -->
                <tr>
                    <td colspan="5" style="height: 1px; background-color: #6c6c6c;"></td>
                </tr>
            </thead>
            <tbody>
            {% for i in tasks %}
                <tr class="{% cycle 'light-bg' 'dark-bg' %}" style="background-color: {% cycle '#3b3b3b' '#2e2e2e' %};">
                    {% if i|get_status_by_user:user.pk != None %}
                        {% if i|get_status_by_user:user.pk == 1 %}
                            <td style="padding: 10px; color: #06a109; font-size: 14px">Accepted</td>
                        {% else %}
                            <td style="padding: 10px; color: #a37604; font-size: 14px">In-Development</td>
                        {% endif %}
                    {% else %}
                        <td style="padding: 10px; color: #9c9c9c; font-size: 14px">None</td>
                    {% endif %}
                    <td style="padding: 10px;">
                        <a href="{% url 'problems:selected_task' pk=i.pk %}" style="color: white; text-decoration: none;">{{ i.name }}</a>
                    </td>
                    <td style="padding: 10px; color: #ffffff;">{{ i.get_count_solutions }}</td>
                    <td style="padding: 10px; color: #ffffff;">{{ i.category }}</td>
                    {% if i.difficulty == 0 %}
                        <td style="padding: 10px; color: #06a109;">Easy</td>
                    {% elif i.difficulty == 1 %}
                        <td style="padding: 10px; color: #a37604;">Medium</td>
                    {% else %}
                        <td style="padding: 10px; color: #d60000;">Hard</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        <nav class="page-navigation">
            {% for i in paginator.page_range %}
                <div style="background-color: #353535; width: 30px; height: 30px; display: inline-block; text-align: center; margin-top: 12px; border-radius: 3px">
                    <a href="?page={{ i }}" style="color: white; text-decoration: none; width: 30px; height: 30px;">{{ i }}</a>
                </div>
            {% endfor %}
        </nav>
    </div>
</div>

    <style>
        .centered-div .btn-group .btn-secondary {
        height: 30px;
        font-size: 13px;
        background-color: #424242;
        margin-top: 10px;
    }

    .task-item {
        padding: 10px;
        border-radius: 3px;
    }

    /* Чередование цветов для списка задач */
    .light-bg {
        background-color: #3a3a3a;
    }
    .dark-bg {
        background-color: #2c2c2c
    }
        @font-face {
        font-family: 'JosefinSans';
        src: url("{% static 'fonts/JosefinSans-VariableFont_wght.ttf' %}") format('truetype');
        font-weight: normal;
        font-style: normal;
        }
    .search-task {
        margin-top: 10px;
        background-color: #444444;
        border-radius: 3px;
        border: 1px solid #8e8e8e; /* Задаем толщину и цвет рамки */
        transition: border-color 0.3s ease;
        color: white;
        font-size: 14px;
    }

    .search-task::placeholder {
        color: #939393;
        font-size: 14px;
        font-family: JosefinSans;
    }

    .search-task:hover {
        border-color: white; /* Цвет рамки при наведении */
    }
    .search-task:focus {
        outline: none;
        border-color: white; /* Цвет рамки при наведении */
    }
        .centered-div h5 {
            font-family: 'JosefinSans', sans-serif;
            font-size: 30px;
        }
        /* Центрируем div */
        .centered-div {
            background: rgb(38, 38, 38); /* Цвет фона как у header */
            color: white;
            width: 60%; /* Ширина div */
            height: 100%;
            padding: 20px; /* Отступы внутри div */
            margin: auto; /* Центрирование по горизонтали */
            margin-top: 20%; /* Отступ сверху для центрирования по вертикали */
            border-radius: 8px; /* Скругление углов */
            text-align: center; /* Текст по центру */
            margin-top: 50px;

        }
    </style>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock body %}
</body>
</html>