src/accounts/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path

from accounts.views import (ChangeEmail, ChangeEmailActivation, ChangePassword,
                            EditProfile, Profile, ResetPassword,
                            ResetPasswordConfirm, UserActivation, UserLogin,
                            UserLogout, UserRegistration)

app_name = "accounts"
urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("reset-password/", ResetPassword.as_view(), name="reset_password"),
    path(
        "password-reset-confirm/<int:pk>/<token>/",
        ResetPasswordConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path("register/", UserRegistration.as_view(), name="register"),
    path("profile/<int:pk>/", Profile.as_view(), name="profile"),
    path("profile/edit/<int:pk>/", EditProfile.as_view(), name="edit_profile"),
    path(
        "profile/edit/change_password/<int:pk>/",
        ChangePassword.as_view(),
        name="change_password",
    ),
    path("profile/edit/change_email/", ChangeEmail.as_view(), name="change_email"),
    path(
        "profile/edit/change_email/confirm/<int:pk>/<str:token>/",
        ChangeEmailActivation.as_view(),
        name="change_email_confirm",
    ),
    path("activate-user/<int:pk>/<str:token>/", UserActivation.as_view(), name="activate"),
    path("logout/", UserLogout.as_view(), name="logout"),
]

src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (GoUserViewSet, ProblemCreateView, ProblemDeleteView,
                       ProblemDetailView, ProblemsListView, ProblemsUpdateView,
                       SolutionGetVew, SolutionListView)

router = routers.DefaultRouter()
router.register("users", GoUserViewSet)
app_name = "api"

# POST gamers/
# GET gamers/
# GET gamers/<id>/
# PUT gamers/<id>/
# PATCH gamers/<id>/
# DELETE gamers/<id>/

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

problems_urls = [
    path(
        "problems/retrieve/<int:pk>",
        ProblemDetailView.as_view(),
        name="problems_detail_api",
    ),
    path("problems/create/", ProblemCreateView.as_view(), name="problems_create_api"),
    path(
        "problems/update/<int:pk>",
        ProblemsUpdateView.as_view(),
        name="problems_update_api",
    ),
    path(
        "problems/delete/<int:pk>",
        ProblemDeleteView.as_view(),
        name="problems_delete_api",
    ),
    path("problems/list/", ProblemsListView.as_view(), name="problems_list"),
]

solution_urls = [
    path("solutions/get/<int:pk>", SolutionGetVew.as_view(), name="solution_get"),
    path("solutions/list/", SolutionListView.as_view(), name="solutions_list"),
]


urlpatterns = [
    path("", include(router.urls)),
    path("docs/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("auth/", include("djoser.urls.jwt")),
]
urlpatterns += problems_urls
urlpatterns += solution_urls

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from common.views import Error404, Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("problems/", include("problems.urls", namespace="problems")),
    path("forum/", include("forum.urls", namespace="forum"))
]
handler404 = Error404.as_view()
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models  # NOQA: F401
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# Create your models here.


class GoUser(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_("Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_("email address"), blank=True, unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    description = models.CharField(
        _("description"),
        max_length=240,
        null=True,
        blank=True,
        help_text=_("Max length is 240 characters."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. " "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    photo = models.ImageField(upload_to="users/photos/", blank=True, null=True)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        verbose_name = _("GoUser")
        verbose_name_plural = _("GoUsers")

    def __str__(self):
        return f"{self.username}"

src/accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model, login, update_session_auth_hash
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Count, Max, Min, Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (CreateView, FormView, RedirectView,
                                  TemplateView, UpdateView)

from accounts.forms import (ChangeEmailForm, ChangePasswordForm,
                            EditProfileForm, ResetPasswordConfirmForm,
                            UserFormRegistration, UserLoginForm)
from accounts.services.email import SendingEmail
from accounts.utils.token_generators import (EmailChangeTokenGenerator,
                                             TokenRegisterGenerator)
from problems.models import Solutions, Tasks

# Create your views here.


class UserLogin(LoginView):
    template_name = "login/login.html"
    form_class = UserLoginForm

    def get_success_url(self):
        return reverse_lazy("index")

    def form_valid(self, form):
        if form.is_valid():
            user = form.cleaned_data.get("user")
            password = form.cleaned_data["password"]

            if user.check_password(password):
                login(self.request, user)
                return super().form_valid(form)
            else:
                return self.form_invalid(form)


class UserLogout(LogoutView):
    next_page = reverse_lazy("accounts:login")


class UserActivation(RedirectView):
    url = reverse_lazy("accounts:profile")

    def get(self, request, pk, token, *args, **kwargs):
        try:
            current_user = get_user_model().objects.get(pk=pk)
        except (get_user_model().DoesNotExist, TypeError, ValueError):
            return HttpResponse("Invalid activation link.(Error)")
        if current_user and TokenRegisterGenerator().check_token(user=current_user, token=token):
            current_user.is_active = True
            current_user.save()

            login(request, current_user)

            return redirect(reverse_lazy("accounts:profile", kwargs={"pk": current_user.pk}))
        else:
            return HttpResponse("Invalid activation link.(without Error)")


class UserRegistration(CreateView):
    form_class = UserFormRegistration
    template_name = "login/registration.html"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.is_active = False
            self.object.save()
            send_email = SendingEmail()
            message = send_email.create_message(
                self.request,
                template_name="activate_account.html",
                user=self.object,
                token=TokenRegisterGenerator().make_token(self.object),
            )
            send_email.send_email(
                subject=settings.EMAIL_REGISTRATION_SUBJECT,
                message=message,
                cc=[
                    settings.EMAIL_HOST_USER,
                ],
                to=(self.object.email,),
            )
        return super().form_valid(form)


class Profile(TemplateView):
    template_name = "profile/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        solutions = Solutions.objects.filter(user_id=kwargs.get("pk")).select_related("task")
        new_context = {
            "solutions_user": solutions,
            "easy": solutions.filter(task__difficulty=0, status=1),
            "mid": solutions.filter(task__difficulty=1, status=1),
            "hard": solutions.filter(task__difficulty=2, status=1),
        }
        all_count_context = {
            "problems_count": Tasks.objects.count(),
            "easy_count_pr": Tasks.objects.filter(difficulty=0).count(),
            "mid_count_pr": Tasks.objects.filter(difficulty=1).count(),
            "hard_count_pr": Tasks.objects.filter(difficulty=2).count(),
        }

        time_memory = {
            "max_time": solutions.aggregate(max_time=Max("time"))["max_time"],
            "min_time": solutions.aggregate(min_time=Min("time"))["min_time"],
            "max_memory": solutions.aggregate(max_memory=Max("memory"))["max_memory"],
            "min_memory": solutions.aggregate(min_memory=Min("memory"))["min_memory"],
        }

        languages = {"count_aggregate_language": Solutions.objects.filter(user_id=kwargs.get("pk")).values("language__language").annotate(count=Count("language"))}

        context.update(new_context)
        context.update(all_count_context)
        context.update(time_memory)
        context.update(languages)

        context["user"] = get_user_model().objects.get(id=kwargs.get("pk"))

        return context


class EditProfile(UpdateView):
    template_name = "profile/edit_profile.html"
    model = get_user_model()
    form_class = EditProfileForm

    def get_success_url(self):
        return reverse_lazy("accounts:profile", kwargs={"pk": self.request.user.pk})

    def form_valid(self, form):
        form.instance.photo = self.request.FILES.get("file")
        return super().form_valid(form)


class ChangePassword(UpdateView):
    template_name = "profile/passwords/change_password.html"
    form_class = ChangePasswordForm
    model = get_user_model()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        if form.is_valid():
            user = self.request.user
            user.set_password(form.cleaned_data["new_password"])
            user.save()

            update_session_auth_hash(self.request, user)

            return redirect(reverse_lazy("accounts:profile", kwargs={"pk": user.pk}))


class ChangeEmail(FormView):
    template_name = "profile/change_email.html"
    form_class = ChangeEmailForm
    model = get_user_model()

    def get_success_url(self):
        return reverse_lazy("accounts:profile", kwargs={"pk": self.request.user.pk})

    def form_valid(self, form):
        if form.is_valid():
            user = self.request.user
            new_email = form.cleaned_data["new_email"]
            send_email = SendingEmail()
            message = send_email.create_message(
                self.request,
                template_name="confirm_email_change_email.html",
                user=user,
                token=EmailChangeTokenGenerator().make_token(user),
                new_email=new_email,
            )

            send_email.send_email(
                subject=settings.EMAIL_REGISTRATION_SUBJECT,
                message=message,
                to=(new_email,),
                cc=[
                    settings.EMAIL_HOST_USER,
                ],
            )
            self.request.session[f"new_email_{user.pk}"] = new_email

        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ChangeEmailActivation(UpdateView):
    def get(self, request, pk, token, *args, **kw):
        try:
            user = get_user_model().objects.get(pk=pk)
        except (get_user_model().DoesNotExist, TypeError, ValueError):
            return HttpResponse("Invalid activation link.(Error)")
        if user and EmailChangeTokenGenerator().check_token(user=user, token=token):
            email = self.request.GET.get("email")
            try:
                session_email = request.session.pop(f"new_email_{user.pk}")
            except KeyError:
                return HttpResponse("Invalid activation link. Email is not valid. Try changing it again.")
            if session_email == email:
                user.email = email
                user.save()
                return redirect(reverse_lazy("accounts:profile", kwargs={"pk": user.pk}))
            else:
                return HttpResponse("Invalid activation link. Email is not valid. Try changing it again.")
        else:
            return HttpResponse("Invalid activation link.(without Error)")


class ResetPassword(View):
    """because through ccbv the uid is used in PasswordResetView and there is heavy logic, it’s better to rewrite it yourself"""

    template_name = "profile/passwords/reset_password.html"
    success_url = reverse_lazy("index")

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")

        try:
            user = get_user_model().objects.get(Q(email=email) | Q(username=email))
        except get_user_model().DoesNotExist:
            return redirect(self.success_url)

        send_email = SendingEmail()
        message = send_email.create_message(
            request,
            template_name="profile/passwords/password_reset_confirm.html",
            user=user,
            token=PasswordResetTokenGenerator().make_token(user),
        )

        send_email.send_email(
            subject=settings.EMAIL_SUBJECT_RESET_PASSWORD,
            message=message,
            to=(user.email,),
        )
        return redirect(self.success_url)


class ResetPasswordConfirm(View):
    success_url = reverse_lazy("accounts:password_reset_complete")
    template_name = "profile/passwords/password_reset_confirm_new.html"
    form_class = ResetPasswordConfirmForm

    def get(self, request, pk, token, *args, **kwargs):
        return render(
            request,
            "profile/passwords/password_reset_confirm_new.html",
            context={"pk": pk, "token": token, "form": self.get_form(request)},
        )

    def post(self, request, pk, token, *args, **kwargs):

src/accounts/templates/profile/change_email.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sign in - GoCode</title>
        <link rel="stylesheet" href="{% static 'css/login.css' %}">
    </head>
    <body>
        <div class="container">
            <img class="logo-under-form" src="{% static 'logos/GoCode_logo_black.svg' %}" alt="" style="width: 120px; height: 120px">
            <form method="post" action="{% url 'accounts:change_email'%}">
                {% csrf_token %}

                {% if form.non_field_errors %}
                    <div class="error-message">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                <div class="form-group">
                    <input placeholder="Password" type="password" id="password" name="password" required>
                    {% if form.password.errors %}
                        <div class="error-message">{{ form.password.errors.0 }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <input placeholder="New email" type="text" id="new_email" name="new_email" required>
                    {% if form.new_password.errors %}
                        <div class="error-message">{{ form.new_password.errors.0 }}</div>
                    {% endif %}
                </div>

                <button type="submit" class="btn" style="font-size: 12px">Change password</button>
            </form>
            <p>don't remember password? <a href="#">reset password</a></p>
        </div>
    </body>
</html>

src/accounts/templates/profile/edit_profile.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
</head>

<body>
{% block body %}
    <style>
        body {
            background: rgb(28, 28, 28);
        }

        .form-control {
            width: 150px;
            height: 25px;
            border-color: #bcbcbc;
            transition: border-color 0.5s ease
        }


        .form-control:hover {
            box-shadow: none;
            border-color: #303030;
        }

        .profile-button {
            background: rgb(99, 39, 120);
            box-shadow: none;
            border: none;
        }

        .profile-button:hover {
            background: #682773;
        }

        .profile-button:focus {
            background: #682773;
            box-shadow: none;
        }

        .profile-button:active {
            background: #682773;
            box-shadow: none;
        }

        .back:hover {
            color: #682773;
            cursor: pointer;
        }

        .labels {
            font-size: 11px;
        }

        .add-experience:hover {
            background: #BA68C8;
            color: #ff0000;
            cursor: pointer;
            border: solid 1px #BA68C8;
        }

                .file-upload {
            position: relative;
            display: inline-block;
            cursor: pointer;
        }

        .file-upload input[type="file"] {
            display: none; /* Скрываем стандартный элемент input */
        }

        .file-upload img {
            width: 120px; /* Задайте ширину изображения */
            height: auto; /* Высота автоматически подстраивается */
            border-radius: 105px; /* Скругление углов */
        }

        div.div-form-to-edit-profile {
            font-family: 'Calibri', sans-serif;
            font-size: 15px;
        }

/* Стилизация скроллбара для WebKit (Chrome, Safari) */
textarea {
    /* Устанавливаем ширину скроллбара */
    scrollbar-width: thin; /* Firefox */
    scrollbar-color: #682773 transparent;
    width: 100%;
    height: 120px;
    border-radius: 6px;
}

/* Для WebKit (Chrome, Safari) */
textarea::-webkit-scrollbar {
    width: 8px; /* Ширина скроллбара */
}

textarea::-webkit-scrollbar-thumb {
    background-color: #682773; /* Цвет скроллбара */
    border-radius: 10px; /* Скругление углов */
}

textarea::-webkit-scrollbar-track {
    background: transparent; /* Фон скроллбара */
}
    </style>
    <div class="container rounded bg-white mt-5 mb-5" >
        <div class="row" >
            <div class="col-md-3 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                        {% if user.photo %}
                            <img class="rounded-circle mt-5" width="150px" src="{{ user.photo.url }}">
                        {% else %}
                            <img class="rounded-circle mt-5" width="150px" src="{% static 'user/photo/base_avatar.png' %}" style="width: 50px; height: 50px">
                        {% endif %}
                        <span class="font-weight-bold">{{ user.username }}</span>
                        <span class="text-black-50">{{ user.email }}</span>
                    </div>
                </div>
            </div>
            <div class="col-md-5 border-right" >
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="text-right">Profile Settings</h4>
                    </div>
                    <div class="div-form-to-edit-profile">
                        <form method="post" action="{% url 'accounts:edit_profile' pk=user.pk %}" class="form-edit-profile" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div>
                                <label class="file-upload">
                                    {% if user.photo %}
                                        <img src="{{ user.photo.url }}" alt="Choose file" />
                                    {% else %}
                                        <img src="{% static 'user/photo/base_avatar.png' %}" alt="Choose file" />
                                    {% endif %}
                                    <input type="file" name="file" accept="image/*" />
                                </label>
                            </div>
                            <div class="form-group row">
                                <label for="username" class="col-sm-3 col-form-label">Username:</label>
                                <div class="col-sm-9">
                                    <input type="text" name="username" id="username" value="{{ user.username }}" class="form-control" style="margin-top: 5px; margin-left: -15px">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea name="description" id="description" class="form-control-textarea" maxlength="240">{{ user.description }}</textarea>
                            </div>
                            <button type="submit" class="btn btn-dark" style="padding: 2px 30px; text-align: center; background-color: #682773">Save</button>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="p-3 py-5">
                    <a class="btn btn-dark" href="{% url 'accounts:change_password' pk=user.pk%}" style="padding: 2px 30px; text-align: center; background-color: #682773">Change password</a>
                                        <a class="btn btn-dark" href="{% url 'accounts:change_email'%}" style="padding: 2px 30px; text-align: center; background-color: #682773; margin-top: 5px">Change email</a>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
</body>
</html>