src/accounts/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path

from accounts.views import (ChangeEmail, ChangeEmailActivation, ChangePassword,
                            EditProfile, Profile, ResetPassword,
                            ResetPasswordConfirm, UserActivation, UserLogin,
                            UserLogout, UserRegistration)

app_name = "accounts"
urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("reset-password/", ResetPassword.as_view(), name="reset_password"),
    path(
        "password-reset-confirm/<int:pk>/<token>/",
        ResetPasswordConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path("register/", UserRegistration.as_view(), name="register"),
    path("profile/<int:pk>/", Profile.as_view(), name="profile"),
    path("profile/edit/<int:pk>/", EditProfile.as_view(), name="edit_profile"),
    path(
        "profile/edit/change_password/<int:pk>/",
        ChangePassword.as_view(),
        name="change_password",
    ),
    path("profile/edit/change_email/", ChangeEmail.as_view(), name="change_email"),
    path(
        "profile/edit/change_email/confirm/<int:pk>/<str:token>/",
        ChangeEmailActivation.as_view(),
        name="change_email_confirm",
    ),
    path("activate-user/<int:pk>/<str:token>/", UserActivation.as_view(), name="activate"),
    path("logout/", UserLogout.as_view(), name="logout"),
]

src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (GoUserViewSet, ProblemCreateView, ProblemDeleteView,
                       ProblemDetailView, ProblemsListView, ProblemsUpdateView,
                       SolutionGetVew, SolutionListView)

router = routers.DefaultRouter()
router.register("users", GoUserViewSet)
app_name = "api"

# POST gamers/
# GET gamers/
# GET gamers/<id>/
# PUT gamers/<id>/
# PATCH gamers/<id>/
# DELETE gamers/<id>/

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

problems_urls = [
    path(
        "problems/retrieve/<int:pk>",
        ProblemDetailView.as_view(),
        name="problems_detail_api",
    ),
    path("problems/create/", ProblemCreateView.as_view(), name="problems_create_api"),
    path(
        "problems/update/<int:pk>",
        ProblemsUpdateView.as_view(),
        name="problems_update_api",
    ),
    path(
        "problems/delete/<int:pk>",
        ProblemDeleteView.as_view(),
        name="problems_delete_api",
    ),
    path("problems/list/", ProblemsListView.as_view(), name="problems_list"),
]

solution_urls = [
    path("solutions/get/<int:pk>", SolutionGetVew.as_view(), name="solution_get"),
    path("solutions/list/", SolutionListView.as_view(), name="solutions_list"),
]


urlpatterns = [
    path("", include(router.urls)),
    path("docs/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("auth/", include("djoser.urls.jwt")),
]
urlpatterns += problems_urls
urlpatterns += solution_urls

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from common.views import Error404, Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("problems/", include("problems.urls", namespace="problems")),
    path("forum/", include("forum.urls", namespace="forum"))
]
handler404 = Error404.as_view()
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/forum/urls.py
from django.urls import path

from forum.views import (Conversations, CreateComment, CreatePost, DetailPost,
                         GeneratorObjects)

app_name = "forum"
urlpatterns = [
    path("", Conversations.as_view(), name="forum"),
    path("<int:pk>/", DetailPost.as_view(), name="detail"),
    path("create-comment/<int:pk>/", CreateComment.as_view(), name="create_comment"),
    path("create-post/", CreatePost.as_view(), name="create_post"),
    path("generate/", GeneratorObjects.as_view(), name="generate")
]

src/problems/urls.py
from django.urls import path

from problems.views import SolvedTask, Task, TaskList

app_name = "problems"
urlpatterns = [
    path("list/", TaskList.as_view(), name="list"),
    path("<int:pk>/", Task.as_view(), name="selected_task"),
    path("<int:pk>/sumbit/", SolvedTask.as_view(), name="solved_task"),
]

src/forum/models.py
from random import choice

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import CASCADE, SET_DEFAULT
from django.utils.translation import gettext_lazy as _
from faker import Faker

from common.models import BaseModel

# Create your models here.


class Conversation(BaseModel):
    title = models.CharField(max_length=100, help_text=_("The maximum number of characters is 100."))
    author = models.ForeignKey(get_user_model(), on_delete=CASCADE)
    content = models.TextField(
        blank=True,
        max_length=5000,
        help_text=_("The maximum number of characters is 5000."),
    )
    image = models.ImageField(upload_to="forum/conversation/images", null=True, blank=True)

    def __str__(self):
        return f"({self.pk}){self.author.username if self.author else 'Unknown'} created: {self.created_at} last updated: {self.last_updated}"

    @classmethod
    def generate_conversations(cls, count):
        conversations = []
        faker = Faker()
        users = get_user_model().objects.all()
        for i in range(count):
            user = choice(users)
            conversation = Conversation(
                title=faker.text(max_nb_chars=100),
                author=user,
                content=faker.text(max_nb_chars=4999),
            )
            conversations.append(conversation)
        Conversation.objects.bulk_create(conversations)


class Comments(BaseModel):
    author = models.ForeignKey(get_user_model(), on_delete=CASCADE)
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField(
        blank=True,
        max_length=2000,
        help_text=_("The maximum number of characters is 2000."),
    )
    image = models.ImageField(upload_to="forum/comments/images", null=True, blank=True)

    def __str__(self):
        return f"{self.author.username if self.author else 'Unknown'} commented: {self.created_at} last updated: {self.last_updated}"

    @classmethod
    def generate_comments(cls, count):
        comments = []
        faker = Faker()
        conversations = Conversation.objects.all()
        users = get_user_model().objects.all()
        for i in range(count):
            conversation = choice(conversations)
            user = choice(users)
            comment = Comments(
                author=user,
                conversation=conversation,
                content=faker.text(max_nb_chars=2000),
            )
            comments.append(comment)
        Comments.objects.bulk_create(comments)

src/forum/views.py
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, TemplateView

from forum.models import Comments, Conversation
from forum.tasks import generate_posts_and_comments


class Conversations(ListView):
    paginate_by = 25
    template_name = "conversations.html"
    queryset = Conversation.objects.all()
    context_object_name = "conversations"

    def get(self, request, *args, **kwargs):
        search_conversation = request.GET.get("search", False)
        if search_conversation:
            self.queryset = self.queryset.filter(title__icontains=search_conversation)
        elif request.GET.get("sorted", False):
            sort_prefix = {
                "all": self.queryset,
                "oldest": self.queryset.order_by('created_at'),
                "newest": self.queryset.order_by('-created_at'),
                "m_comments": self.queryset.annotate(count_comments=Count("comments")).order_by("-count_comments"),
                "l_comments": self.queryset.annotate(count_comments=Count("comments")).order_by("count_comments"),
            }
            self.queryset = sort_prefix.get(request.GET.get("sorted", False))
        return super().get(request, *args, **kwargs)


class DetailPost(TemplateView):
    template_name = "detail_post.html"

    def get_context_data(self, **kwargs):
        pk = kwargs.get("pk")
        conversation = Conversation.objects.get(pk=pk)
        comments = Comments.objects.filter(conversation=conversation).order_by("created_at")
        return super().get_context_data(conversation=conversation, comments=comments, **kwargs)


class CreateComment(CreateView):
    model = Comments

    def post(self, request, *args, **kwargs):
        pk = kwargs.get("pk")
        try:
            conversation = Conversation.objects.get(pk=pk)
        except Conversation.DoesNotExist:
            return HttpResponse("Conversation not found")
        Comments.objects.create(author=self.request.user, conversation=conversation, content=request.POST.get("reply"))
        return redirect(reverse_lazy("forum:detail", kwargs={"pk": pk}))


class CreatePost(CreateView):
    model = Conversation
    template_name = "create_post.html"
    fields = ["title", "content", "image"]

    def post(self, request, *args, **kwargs):
        title = request.POST.get("title")
        content = request.POST.get("content")
        conversation = Conversation.objects.create(title=title, content=content, author=self.request.user, image=request.FILES.get("image"))
        return redirect(reverse_lazy("forum:detail", kwargs={"pk": conversation.pk}))


class GeneratorObjects(View):
    """Before using it, it is better to familiarize yourself with how the generation method works in models"""
    def get(self, request, *args, **kwargs):
        generate_posts_and_comments.delay(request.GET.get("posts", 1), request.GET.get("comments", 5))
        return HttpResponse("Add task")

src/forum/templates/conversations.html
{% load static %}
{% load forum_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forum</title>
    <link rel="stylesheet" href={% static 'css/forum.css' %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <header>
        <!--NavBar Section-->
        <div class="navbar">
            <nav class="navigation hide" id="navigation">
                <span class="close-icon" id="close-icon" onclick="showIconBar()"><i class="fa fa-close"></i></span>
                <ul class="nav-list">
                    <li class="nav-item"><a href="#">News</a></li>
                    <li class="nav-item"><a href="{% url 'problems:list' %}">Problems</a></li>
                    <li class="nav-item"><a href="{% url 'index' %}">Home</a></li>
                </ul>
            </nav>
            <a class="bar-icon" id="iconBar" onclick="hideIconBar()"><i class="fa fa-bars"></i></a>
            <div class="brand">gc community</div>
        </div>
        <!--SearchBox Section-->
            <div class="search-box">
                <div>
                <form method="get" action="{% url 'forum:forum' %}">
                    <div class="dropdown">
                        <button class="dropdown-button">Sorted by <i class="fa fa-arrow-down"></i></button>
                        <div class="dropdown-content">
                            <a href="{% url 'forum:forum' %}?sorted=oldest&page=1">Oldest</a>
                            <a href="{% url 'forum:forum' %}?sorted=newest&page=1">Newest</a>
                            <a href="{% url 'forum:forum' %}?sorted=m_comments&page=1">Most comments</a>
                            <a href="{% url 'forum:forum' %}?sorted=l_comments&page=1">Least comments</a>
                        </div>
                    </div>
                    <input type="text" name="search" placeholder="search ...">
                    <button type="submit"><i class="fa fa-search"></i></button>
                    <a style="margin-left: 15px " href="{% url 'forum:create_post' %}" type="submit"><i class="fa fa-plus"></i></a>
                </form>
                </div>
            </div>
    </header>
    <div class="container">
        <div class="subforum">
            <div class="subforum-title">
                <h1>Main information</h1>
            </div>
            <div class="subforum-row">
                <div class="subforum-icon subforum-column center">
                    <i class="fa fa-newspaper-o center"></i>
                </div>
                <div class="subforum-description subforum-column">
                    <h4><a href="#">Description Title</a></h4>
                    <p>Description Content: let's try to be cool, otherwise,w at 'sthe point in libing together with people youdont' live.</p>
                </div>
                <div class="subforum-stats subforum-column center">
                    <span>24 Posts | 12 Topics</span>
                </div>
                <div class="subforum-info subforum-column">
                    <b><a href="">Last post</a></b> by <a href="">JustAUser</a>
                    <br>on <small>12 Dec 2020</small>
                </div>
            </div>
        </div>
        <!--More-->

        <div class="subforum">
            <div class="subforum-title">
                <h1>All posts</h1>
            </div>
            {% for i in conversations %}
                <div class="subforum-row">
                    <div class="subforum-icon subforum-column center">
                        <i class="fa fa-code center"></i>
                    </div>
                    <div class="subforum-description subforum-column">
                        <h4><a href="{% url 'forum:detail' pk=i.pk %}">{{ i.title }}</a></h4>
                        <p style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; width: 100%; font-size: 14px">{{ i.content }}</p>
                    </div>
                    <div class="subforum-stats subforum-column center">
                        <span>{{ i|get_count_comments }} Comments</span>
                    </div>
                    <div class="subforum-info subforum-column">
                        {% get_newest_comment_by_post i as newest_comment %}
                        <b><a href="{% url 'forum:detail' pk=i.pk %}"></a> Last comment</b>
                        {% if newest_comment %}
                            by <a href="{% url 'accounts:profile' pk=newest_comment.author.pk %}">{{ newest_comment.author.username }}</a>
                        {% else %}
                            No comments yet.
                        {% endif %}
                        <br>on <small>{{ newest_comment.created_at }}</small>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!---->
    <div>
        <nav class="pagination">
            {% for i in paginator.page_range %}
                <a href="?sorted={{ request.GET.sorted|default:'all' }}&page={{ i }}">{{ i }}</a>
            {% endfor %}
        </nav>
    </div>
    </div>

    <!-- Forum Info -->
    <div class="forum-info">
        <div class="chart">
            MyForum - Stats &nbsp;<i class="fa fa-bar-chart"></i>
        </div>
        <span><u>5,369</u> Posts in <u>48</u> Topics by <u>8,124</u> Members.</span><br>
        <span>Latest post: <b><a href="">Random post</a></b> on Dec 15 2021 By <a href="">RandomUser</a></span>.<br>
        <span>Check <a href="">the latest posts</a> .</span><br>
    </div>

    <footer>
        <span>&copy;  Selmi Abderrahim | All Rights Reserved</span>
    </footer>
    <script src={% static 'js/forum.js' %}></script>
</body>
</html>

src/forum/templates/create_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
    <link rel="stylesheet" href="{% static 'css/create_post.css' %}">
</head>
<body>
    <div class="form-container">
        <h1>Create a Post</h1>
        <form action="{% url 'forum:create_post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Post Title</label>
                <input type="text" id="title" name="title" placeholder="Enter your title" required>
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <textarea id="content" name="content" rows="5" placeholder="Write something..." required></textarea>
            </div>
            <div class="form-group">
                <label for="photo">Upload Photo</label>
                <input type="file" id="image" name="image">
            </div>
            <button type="submit" class="submit-btn">Submit</button>
        </form>
    </div>
</body>
</html>

src/forum/templates/detail_post.html
{% load static %}
{% load forum_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forum</title>
    <link rel="stylesheet" href={% static 'css/forum.css' %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <header>
        <!--NavBar Section-->
        <div class="navbar">
            <nav class="navigation hide" id="navigation">
                <span class="close-icon" id="close-icon" onclick="showIconBar()"><i class="fa fa-close"></i></span>
                <ul class="nav-list">
                    <li class="nav-item"><a href="#">News</a></li>
                    <li class="nav-item"><a href="{% url 'problems:list' %}">Problems</a></li>
                    <li class="nav-item"><a href="{% url 'index' %}">Home</a></li>
                </ul>
            </nav>
            <a class="bar-icon" id="iconBar" onclick="hideIconBar()"><i class="fa fa-bars"></i></a>
            <div class="brand">gc community</div>
        </div>
        <!--SearchBox Section-->
            <div class="search-box">
                <div>
                <form method="get" action="{% url 'forum:forum' %}">
                    <div class="dropdown">
                        <button class="dropdown-button">Sorted by <i class="fa fa-arrow-down"></i></button>
                        <div class="dropdown-content">
                            <a href="{% url 'forum:forum' %}?sorted=oldest&page=1">Oldest</a>
                            <a href="{% url 'forum:forum' %}?sorted=newest&page=1">Newest</a>
                            <a href="{% url 'forum:forum' %}?sorted=m_comments&page=1">Most comments</a>
                            <a href="{% url 'forum:forum' %}?sorted=l_comments&page=1">Least comments</a>
                        </div>
                    </div>
                    <input type="text" name="search" placeholder="search ...">
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
                </div>
            </div>
    </header>
    <div class="container">

        <!--Topic Section-->
        <div class="topic-container">
            <!--Original thread-->
            <div class="head">
                <div class="authors">Author: {{ conversation.author.username }}</div>
                <div class="content"></div>
            </div>

            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">{{ conversation.author.username }}</a></div>
                    {% if conversation.author.is_staff %}
                        <div>Admin</div>
                    {% else %}
                        <div>User</div>
                    {% endif %}
                    <a href="{% url 'accounts:profile' pk=conversation.author.pk %}">
                        {% if conversation.author.photo %}
                        <img src="{{ conversation.author.photo.url }}" alt="" style="width: 200px; height: 50px; border-radius: 5px">
                        {% else %}
                            <img src="{% static 'user/photo/base_avatar.png' %}" alt="" style="width: 40px; height: 40px; border-radius: 20px">
                        {% endif %}
                    </a>
                    <div>Posts: <span>{% get_all_posts_by_user conversation.author.pk %}</span></div>
                    <div>Comments: <span>{% get_all_comments_by_user conversation.author.pk %}</span></div>
                    <div class="time">
                        <span>Date: {{ conversation.created_at }}</span>
                    </div>
                </div>
                <div class="content">
                    {{ conversation.content }}
                    {% if conversation.image %}
                        <a href="{{ conversation.image.url }}"><img src="{{ conversation.image.url }}" alt="" style="width: 38%; height: 42%; border-radius: 5px"></a>
                    {% endif %}
                    <div class="comment">
                        <button onclick="showComment()">Comment</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="head">
                <div class="authors">Total: {{ comments.count }} comments</div>
        </div>


        <!--Comment Area-->
        <div class="comment-area hide" id="comment-area">
            <form action="{% url 'forum:create_comment' pk=conversation.pk %}" method="post">
                {% csrf_token %}
                <textarea name="reply" id="" placeholder="reply here ... "></textarea>
                <button type="submit" value="submit">Submit</button>
            </form>
        </div>

        <!--Comments Section-->
        {% for i in comments %}
        <div class="comments-container">
            <div class="body">
                <div class="authors">
                    <div class="username"><a href="">{{ i.author.username }}</a></div>
                    {% if i.author.is_staff %}
                        <div>Admin</div>
                    {% else %}
                        <div>User</div>
                    {% endif %}
                    <a href="{% url 'accounts:profile' pk=i.author.pk %}">
                        {% if i.author.photo %}
                        <img src="{{ i.author.photo.url }}" alt="" style="width: 200px; height: 50px; border-radius: 5px">
                        {% else %}
                            <img src="{% static 'user/photo/base_avatar.png' %}" alt="" style="width: 40px; height: 40px; border-radius: 20px">
                        {% endif %}
                    </a>
                    <div>Posts: <u>{% get_all_posts_by_user i.author.pk %}</u></div>
                    <div>Comments: <u>{% get_all_comments_by_user i.author.pk %}</u></div>
                    <div class="time">
                        <span>Date: {{ i.created_at }}</span>
                    </div>
                </div>
                <div class="content">
                    {{ i.content }}
                    <div class="comment">
                        <button onclick="showReply()">Reply</button>
                    </div>
                </div>
            </div>
        </div>
        <!--Reply Area-->
        <div class="comment-area hide" id="reply-area">
            <form action="#" method="post">
                {% csrf_token %}
                <textarea name="reply" id="" placeholder="reply here ... "></textarea>
                <button type="submit" value="submit">Submit</button>
            </form>
        </div>
        {% endfor %}
    </div>
    <footer>
        <span>&copy;  Selmi Abderrahim | All Rights Reserved</span>
    </footer>
    <script src={% static 'js/forum.js' %}></script>
</body>
</html>