src/accounts/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path

from accounts.views import (ChangeEmail, ChangeEmailActivation, ChangePassword,
                            EditProfile, Profile, ResetPassword,
                            ResetPasswordConfirm, UserActivation, UserLogin,
                            UserLogout, UserRegistration)

app_name = "accounts"
urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("reset-password/", ResetPassword.as_view(), name="reset_password"),
    path(
        "password-reset-confirm/<int:pk>/<token>/",
        ResetPasswordConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path("register/", UserRegistration.as_view(), name="register"),
    path("profile/<int:pk>/", Profile.as_view(), name="profile"),
    path("profile/edit/<int:pk>/", EditProfile.as_view(), name="edit_profile"),
    path(
        "profile/edit/change_password/<int:pk>/",
        ChangePassword.as_view(),
        name="change_password",
    ),
    path("profile/edit/change_email/", ChangeEmail.as_view(), name="change_email"),
    path(
        "profile/edit/change_email/confirm/<int:pk>/<str:token>/",
        ChangeEmailActivation.as_view(),
        name="change_email_confirm",
    ),
    path("activate-user/<int:pk>/<str:token>/", UserActivation.as_view(), name="activate"),
    path("logout/", UserLogout.as_view(), name="logout"),
]

src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (GoUserViewSet, ProblemCreateView, ProblemDeleteView,
                       ProblemDetailView, ProblemsListView, ProblemsUpdateView,
                       SolutionGetVew, SolutionListView)

router = routers.DefaultRouter()
router.register("users", GoUserViewSet)
app_name = "api"

# POST gamers/
# GET gamers/
# GET gamers/<id>/
# PUT gamers/<id>/
# PATCH gamers/<id>/
# DELETE gamers/<id>/

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

problems_urls = [
    path(
        "problems/retrieve/<int:pk>",
        ProblemDetailView.as_view(),
        name="problems_detail_api",
    ),
    path("problems/create/", ProblemCreateView.as_view(), name="problems_create_api"),
    path(
        "problems/update/<int:pk>",
        ProblemsUpdateView.as_view(),
        name="problems_update_api",
    ),
    path(
        "problems/delete/<int:pk>",
        ProblemDeleteView.as_view(),
        name="problems_delete_api",
    ),
    path("problems/list/", ProblemsListView.as_view(), name="problems_list"),
]

solution_urls = [
    path("solutions/get/<int:pk>", SolutionGetVew.as_view(), name="solution_get"),
    path("solutions/list/", SolutionListView.as_view(), name="solutions_list"),
]


urlpatterns = [
    path("", include(router.urls)),
    path("docs/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("auth/", include("djoser.urls.jwt")),
]
urlpatterns += problems_urls
urlpatterns += solution_urls

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from common.views import Error404, Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("problems/", include("problems.urls", namespace="problems")),
    path("forum/", include("forum.urls", namespace="forum"))
]
handler404 = Error404.as_view()
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/forum/urls.py
from django.urls import path

from forum.views import (Conversations, CreateComment, CreatePost, DetailPost,
                         GeneratorObjects)

app_name = "forum"
urlpatterns = [
    path("", Conversations.as_view(), name="forum"),
    path("<int:pk>/", DetailPost.as_view(), name="detail"),
    path("create-comment/<int:pk>/", CreateComment.as_view(), name="create_comment"),
    path("create-post/", CreatePost.as_view(), name="create_post"),
    path("generate/", GeneratorObjects.as_view(), name="generate")
]

src/problems/urls.py
from django.urls import path

from problems.views import SolvedTask, Task, TaskList

app_name = "problems"
urlpatterns = [
    path("list/", TaskList.as_view(), name="list"),
    path("<int:pk>/", Task.as_view(), name="selected_task"),
    path("<int:pk>/sumbit/", SolvedTask.as_view(), name="solved_task"),
]

src/common/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import SET_DEFAULT

# Create your models here.


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

src/common/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View

# Create your views here.


class Error404(View):
    def get(self, request, exception):
        return render(request, "errors/404.html", status=404)


class Index(TemplateView):
    template_name = "index.html"

src/common/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Go - code</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/product/">
    <link href="https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link href="{% static 'css/index.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
</head>

<header class="site-header sticky-top py-1" style="background: rgb(38,38,38); border-bottom: 1px solid #555;">
    <nav class="selection-of-partitions d-flex justify-content-between align-items-center">
        <div class="left-links d-flex">
            <a class="py-2" href="/" aria-label="Product">
                <img class="selection-of-partitions-img" src="{% static 'logos/GoCode_logo_white.svg' %}" alt="Product Icon" width="40px" height="25px" style="opacity: 0.5">
            </a>
            <a class="py-2 d-none d-md-inline-block" href="#" style="text-decoration: none;">News</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'forum:forum' %}" style="text-decoration: none;">Forum</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'problems:list' %}" style="text-decoration: none;">Problems</a>
            <a class="py-2 d-none d-md-inline-block" href="https://github.com/snickyyy/GoCode" style="text-decoration: none;">Github</a>
            <a class="py-2 d-none d-md-inline-block" href="#" style="text-decoration: none;">Support</a>
            <a class="py-2 d-none d-md-inline-block" href="#" style="text-decoration: none;">Pricing</a>
            <a class="py-2 d-none d-md-inline-block" href="#" style="text-decoration: none;">Cart</a>
        </div>
        <div class="right-link">
            {% if user.is_authenticated %}
                <div style="display: flex; align-items: center; gap: 10px; margin-right: 140px;">
                <span style="font-size: 14px; color: #8e8e8e;">{{ user.username }}</span> <!-- Установите нужный цвет -->
                    <a href="{% url 'accounts:profile' pk=user.pk %}">
                        {% if user.photo %}
                        <img src="{{ user.photo.url }}" alt="" style="width: 40px; height: 40px; border-radius: 20px">
                        {% else %}
                            <img src="{% static 'user/photo/base_avatar.png' %}" alt="" style="width: 40px; height: 40px; border-radius: 20px">
                        {% endif %}
                    </a>
                </div>
            {% else %}
                <div style="display: flex; align-items: center; gap: 8px; margin-right: 280px;">
                    <a class="btn btn-outline-secondary" href="{% url 'accounts:register' %}" style="height: 35px; font-size: 15px; padding-top: 5px;">Register</a>
                    <span style="font-size: 15px; color: #8e8e8e;">or</span> <!-- Установите нужный цвет -->
                    <a class="btn btn-outline-secondary" href="{% url 'accounts:login' %}" style="height: 35px; font-size: 15px; padding-top: 5px;">Sign in</a>
                </div>

            {% endif %}
        </div>
    </nav>
</header>

<body>
    {% block body %}
    {% endblock body%}
</body>

<footer class="container py-5">
    <div class="row">
        <div class="col-12 col-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor"
                 stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img"
                 viewBox="0 0 24 24"><title>Product</title>
                <circle cx="12" cy="12" r="10"/>
                <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/>
            </svg>
            <small class="d-block mb-3 text-muted">&copy; 2017–2022</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="link-secondary" href="#">Cool stuff</a></li>
                <li><a class="link-secondary" href="#">Random feature</a></li>
                <li><a class="link-secondary" href="#">Team feature</a></li>
                <li><a class="link-secondary" href="#">Stuff for developers</a></li>
                <li><a class="link-secondary" href="#">Another one</a></li>
                <li><a class="link-secondary" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="link-secondary" href="#">Resource name</a></li>
                <li><a class="link-secondary" href="#">Resource</a></li>
                <li><a class="link-secondary" href="#">Another resource</a></li>
                <li><a class="link-secondary" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="link-secondary" href="#">Business</a></li>
                <li><a class="link-secondary" href="#">Education</a></li>
                <li><a class="link-secondary" href="#">Government</a></li>
                <li><a class="link-secondary" href="#">Gaming</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="link-secondary" href="#">Team</a></li>
                <li><a class="link-secondary" href="#">Locations</a></li>
                <li><a class="link-secondary" href="#">Privacy</a></li>
                <li><a class="link-secondary" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>

</html>

src/common/templates/index.html
{% extends 'base.html' %}
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Go - code</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/product/">
    <link href="https://getbootstrap.com/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link href="{% static 'css/index.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
</head>
<body>


<main>
    {% block body %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 fw-normal">Welcome to Go-Code</h1>
            <p class="lead fw-normal">We are very glad to see you on our site. Come on, start your journey in a place with us right now!</p>
            <a class="btn btn-outline-secondary" href="{% url 'accounts:login' %}" style="width: 110px">Sign in</a>
        </div>
        <div class="product-device shadow-sm d-none d-md-block">
            <img src="{% static 'logos/Terminal.svg' %}" alt="Product Icon" width="200px" height="300px" style="margin-top: 85px; opacity: 0.3;">
        </div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block">
            <img src="{% static 'logos/GoCode_logo_black.svg' %}" alt="Product Icon" width="200px" height="300px" style="margin-top: 120px; opacity: 0.3;">
        </div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
        <div class="text-bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 py-3">
                <h2 class="display-5">First time on Go-Code?</h2>
            </div>
            <div class="bg-light shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;">
                <p class="lead" style="color: black; font-size: 25px; padding-top: 80px;">Register here and start your training on Go-Code right now!</p>
                <a class="btn btn-outline-secondary" href="{% url 'accounts:register' %}" style="width: 110px">Register</a>
            </div>
        </div>
        <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 p-3">
                <h2 class="display-5">Why Go-Code?</h2>
            </div>
            <div class="bg-dark shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;">
                <p class="lead" style="color: white; font-size: 25px; padding-top: 80px; padding-left: 5px; padding-right: 5px">Go-Code it the best platform where you can practice your skills in problems, get an assessment of your algorithm and also look at the solutions of others!</p>
                <a class="btn btn-outline-light" href="#" style="width: 110px;">Check news</a>
            </div>
        </div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
        <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 p-3">
                <h2 class="display-5">Another headline1</h2>
                <p class="lead">And an even wittier subheading.</p>
            </div>
            <div class="bg-dark shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
        </div>
        <div class="text-bg-primary me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 py-3">
                <h2 class="display-5">Another headline2</h2>
                <p class="lead">And an even wittier subheading.</p>
            </div>
            <div class="bg-light shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
        </div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
        <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 p-3">
                <h2 class="display-5">Another headline3</h2>
                <p class="lead">And an even wittier subheading.</p>
            </div>
            <div class="bg-body shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
        </div>
        <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 py-3">
                <h2 class="display-5">Another headline4</h2>
                <p class="lead">And an even wittier subheading.</p>
            </div>
            <div class="bg-body shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
        </div>
    </div>

    <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
        <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 p-3">
                <h2 class="display-5">Another headline5</h2>
                <p class="lead">And an even wittier subheading.</p>
            </div>
            <div class="bg-body shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
        </div>
        <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 py-3">
                <h2 class="display-5">Another headline6</h2>
                <p class="lead">And an even wittier subheading.</p>
            </div>
            <div class="bg-body shadow-sm mx-auto"
                 style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
        </div>
    </div>
    {% endblock body %}
</main>

<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>


</body>
</html>